config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'appointments/new'
  root "doctors#index"

  resources :users
  resources :doctors do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :doctors, through: :appointments

    def full_name
      "#{self.first_name} #{self.last_name}" 
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor
  def index
    @physicians = @doctor.appointments.where(role: 'physician')
    @nurses = @doctor.appointments.where(role: 'nurse')
    @patients = @doctor.appointments.where(role: 'patient')
  end

  def new
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)
    else
      render :new
    end

  end

  def destroy
    @appointment = @doctor.appointments.find(params[:id])
    @appointment.destroy
    redirect_to doctor_appointments_path(@doctor)
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:doctor_id])
    end
   
    def appointment_params
      params.require(:appointment).permit(:role, :user_id)
    end



end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.create(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else 
      render :new
    end
  end

  def destroy
   @doctor.destroy
   redirect_to doctors_path
  end

  private
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/index.html.erb
<h1><%= @doctor.name %>: Appointments</h1>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor) %>
<hr />

<h2>Physician</h2>
<ul>
   <%= @physicians.each do |physician| %>
   <br />
   <%= link_to 'Remove', doctor_appointment_path(@doctor, physician), method: :delete %>
</li>
<% end %>
</ul>
<h2>Nurse</h2>
<ul>
  <%= @nurses.each do |nurse| %>
    <li>
      <%= nurse.user.full_name %>
      <br />
      <%= link_to 'Remove', doctor_appointment_path(@doctor, nurse), method: :delete %>
    </li>
    <% end %>
</ul>
<h2>Patient</h2>
<ul>
  <%= @patients.each do |patient| %>
  <li>
   <%= patient.full_name %>
   <br />
   <%= link_to 'Remove', doctor_appointment_path(@doctor, patient), method: :delete %>
  </li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Add Appointment</h1>
<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :user_id %>
  <%= f.select :user_id, @users.collect { |u| [u.first_name] } %>
  <br />
  <%= f.label :role %>
  <%= f.select :role, ['nurse', 'pyshician', 'patient'] %>
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
  <% end %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<%= link_to 'Add Doctor', new_doctor_path %>
<hr />
<h2><%= @doctors.length <= 0 ? "No Doctors" : "" %></h2>
<ul>
  <% @doctors.each do |doctor| %>
     <li>
      <%= link_to doctor.name, @doctor %>
     </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Doctor name" %>
  </div>
  <div>
    <%= f.label :Title %>
    <%= f.text_field :title, required: true %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
  <% end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', doctor_appointments_path(@doctor), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Doctor", @doctor, method: :delete, class: "ui red button inverted" %>

app/views/layouts/_navbar.html.erb
<nav class="ui pointing menu">

  <%= link_to "Doctors", doctors_path, class: "item" %>
  <%= link_to "Add doctors", new_doctor_path, class: "item" %>
  <%= link_to "Users", users_path, class: "item" %>
  <%= link_to "Add user", new_user_path, class: "item" %>





</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocAppoints</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'Add User', new_user_path %>
<hr />
<ul>
  <% @users.each do |user| %>
   <li> 
     <%= link_to user.full_name, user %>
   </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
<div class="field">
   <%= f.label :first_name %>
   <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
</div>
<div class="field">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true, placeholder: "last_name" %>

</div>
<%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul> 
   <% @user.doctors.each do |doctor| %>
   <li>
     <%= link_to doctor.name, doctor %>
   </li>
   <% end %>
</ul>
<br />
<br />
<br />
<%= link_to "Delete User", @user, method: :delete, class: "ui red button inverted" %>